# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HyReadExam_Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'SDWebImage', '5.0'
  pod 'FMDB', '2.7.5'
  # Pods for HyReadExam_Swift

  target 'HyReadExam_SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HyReadExam_SwiftUITests' do
    # Pods for testing
  end

end
